#!/usr/bin/env bash

__puton__ () {
  __python='python3'
  __pip='pip3'
  __root=$(pwd)
  __site='site'
  __templates='templates'
  __core=$(dirname $(realpath $BASH_SOURCE))
}

install__ () {
  mkdir -p $__core/$__site
  $__pip install -r $__core/lib/requirements.txt
}

create__help='@arg project name @does initiate a project in current folder.'
create__ () {
  local project_name=$1
  test -z $project_name && read -p'Project name? ' project_name
  test -d $__root/$project_name && echo 'Project already exists.' && return
  __root=$__root/$project_name
  __exec mkdir -p $__root
  rsync -av $__core/$__templates/ $__root/$__templates
  rsync -av $__core/.gitignore $__root/
}

serve__ () {
  local port=${1}
  cd $__root/$__site
  $__python -m http.server $port
}

build__ () {
  $__python $__core/lib/supersimple.py --templates=$__root/$__templates --site=$__site
  rsync -a $__root/$__templates/assets $__root/$__site
}

source $(dirname $(realpath $BASH_SOURCE))/vendor/autoload.sh
