#!/usr/bin/env bash

__puton__ () {
  __python='python3'
  __pip='pip3'
  __root=$(pwd)
  __site='site'
  __templates='templates'
}

install__ () {
  mkdir -p $__root/$__site
  $__pip install -r $__root/lib/requirements.txt
}

serve__ () {
  local port=${1}
  cd $__root/$__site
  $__python -m http.server $port
}

build__ () {
  $__python $__root/lib/supersimple.py --templates=$__templates --site=$__site
}

source $(dirname $(realpath $BASH_SOURCE))/vendor/autoload.sh

